package es.in2.issuer.backend.shared.domain.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialRequestTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String credentialConfigurationId = "LEARCredentialEmployee";
        String expectedFormat = "jwt_vc_json";
        Proof expectedProof = new Proof("jwt", "eyJhbGciOiJFUzI1NiIsInR5cCI6Im9wZW5pZDR2Y2ktcHJvb2Yrand0Iiwia2lkIjoiZGlkOmtleTp6Nk1rdC4uLiJ9");
        // Act
        CredentialRequest credentialRequest = new CredentialRequest(credentialConfigurationId, expectedFormat, expectedProof);
        // Assert
        assertEquals(credentialConfigurationId, credentialRequest.credentialConfigurationId());
        assertEquals(expectedFormat, credentialRequest.format());
        assertEquals(expectedProof, credentialRequest.proof());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String credentialConfigurationId = "LEARCredentialEmployee";
        String expectedFormat = "jwt_vc_json";
        Proof expectedProof = new Proof("jwt", "eyJhbGciOiJFUzI1NiIsInR5cCI6Im9wZW5pZDR2Y2ktcHJvb2Yrand0Iiwia2lkIjoiZGlkOmtleTp6Nk1rdC4uLiJ9");
        // Act
        CredentialRequest dto1 = new CredentialRequest(credentialConfigurationId, expectedFormat, expectedProof);
        CredentialRequest dto2 = new CredentialRequest(credentialConfigurationId, expectedFormat, expectedProof);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}