package es.in2.issuer.backend.shared.domain.model.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String transactionId = "1234";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        // Act
        CredentialResponse responseDTO = new CredentialResponse(expectedCredential, transactionId, expectedCNonce, expectedCNonceExpiresIn);
        // Assert
        assertEquals(expectedCredential, responseDTO.credentials());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String transactionId = "1234";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        // Act
        CredentialResponse dto1 = new CredentialResponse(expectedCredential, transactionId, expectedCNonce, expectedCNonceExpiresIn);
        CredentialResponse dto2 = new CredentialResponse(expectedCredential, transactionId, expectedCNonce, expectedCNonceExpiresIn);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}