package es.in2.issuer.backend.shared.domain.model.dto;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String transactionId = "1234";
        List<CredentialResponse.Credential> expectedCredentials = List.of(
                CredentialResponse.Credential.builder()
                        .credential("LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L")
                        .build());
        // Act
        CredentialResponse responseDTO = new CredentialResponse(expectedCredentials, transactionId);
        // Assert
        assertEquals(expectedCredentials, responseDTO.credentials());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String transactionId = "1234";
        CredentialResponse.Credential expectedCredential = CredentialResponse.Credential.builder()
                .credential("LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L")
                .build();
        // Act
        CredentialResponse dto1 = new CredentialResponse(List.of(expectedCredential), transactionId);
        CredentialResponse dto2 = new CredentialResponse(List.of(expectedCredential), transactionId);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}