package es.in2.issuer.backend.shared.domain.model.dto;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ProofTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String proofType = "jwt";
        String expectedJwt = "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiw....WZwmhmn9OQp6YxX0a2L";
        // Act
        Proof proof = new Proof(proofType, expectedJwt);
        // Assert
        assertEquals(expectedJwt, proof.jwt());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String proofType = "jwt";
        String expectedJwt = "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiw....WZwmhmn9OQp6YxX0a2L";
        // Act
        Proof dto1 = new Proof(proofType, expectedJwt);
        Proof dto2 = new Proof(proofType, expectedJwt);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}